project:
  type: book
  output-dir: docs

book:
  title: "Using Causal Questions for Theory Development"
  author: "D. Alex Hughes"
  date: "7/22/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - finding_theories.qmd 
    - theories_to_questions.qmd 
    - causal_implications.qmd 
    - ideal_experiments.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    embed-resources: true
  pdf:
    documentclass: scrreprt



